aws:
  endpoint-client: ${ENDPOINT_CLIENT:http://localhost:4566}
sqs:
  queue: ${AUTO_CREATE_QUEUES:DEV_IFOOD_CATALOG_PRODUCT_VIOLATION,DEV_IFOOD_CATALOG_CATEGORY_VIOLATION,DEV_IFOOD_CATALOG_IMAGE_VIOLATION}
server:
  port: 9000

cloud:
  aws:
    sqs:
      endpoint: ${ENDPOINT_CONSUMER:""}
      handler:
        default-deletion-policy: never
      listener:
        visibility-timeout: 10
      enabled: ${ENABLED_CONSUMER:false}
